services:
  - type: web
    name: asnodt
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
        description: "MongoDB connection string (will be set in Render dashboard)"
      - key: PORT
        value: 10000
        description: "Port for the web server" 